<?php
if ( ! function_exists('get_list_active_inactive')) {
    function get_list_active_inactive()
    {
        return [
            1 => __('general.active'),
            2 => __('general.inactive')
        ];
    }
}
if ( ! function_exists('get_list_enable_disable')) {
    function get_list_enable_disable()
    {
        return [
            1 => __('general.enable'),
            2 => __('general.disabled')
        ];
    }
}

if ( ! function_exists('get_list_show_hide')) {
    function get_list_show_hide()
    {
        return [
            1 => __('general.hide'),
            2 => __('general.show')
        ];
    }
}

if ( ! function_exists('get_list_type_user')) {
    function get_list_type_user()
    {
        return [
            1 => __('general.project'),
            2 => __('general.interaction_based')
        ];
    }
}

if ( ! function_exists('get_list_lang')) {
    function get_list_lang()
    {
        return [
            'id' => 'Indonesia',
            'en' => 'English'
        ];
    }
}

if ( ! function_exists('get_list_module')) {
    function get_list_module()
    {
        return [
            '' => 'None',
            '/profile/edit' => 'Profile',
            '/feedbacks' => 'Feedback',
            '/performances' => 'Performance',
        ];
    }
}



if ( ! function_exists('get_list_city')) {
    function get_list_city()
    {
        return [
            'Aceh' => [
                'Kabupaten Aceh Barat' =>[
                    'Johan Pahlawan',
                    'Samatiga',
                    'Bubon',
                    'Arongan Lambalek',
                    'Woyla',
                    'Woyla Barat',
                    'Woyla Timur',
                    'Kaway XVI',
                    'Meureubo',
                    'Pante Ceureumen',
                    'Panton Reu',
                    'Sungai Mas',
                    ],
                'Kabupaten Aceh Barat Daya' => [
                    'Blang Pidie',
                    'Tangan-Tangan',
                    '	Manggeng',
                    'Susoh',
                    'Kuala Batee',
                    'Babah Rot',
                    '	Setia',
                    '	Jeumpa',
                    'Lembah Sabil',
                ],
                'Kabupaten Aceh Besar' => [
                    'Baitussalam',
                    'Blang Bintang',
                    'Darul Imarah',
                    'Darul Kamal',
                    'Darussalam',
                    'Indrapuri',
                    'Ingin Jaya',
                    'Kota Jantho',
                    'Krueng Barona Jaya',
                    'Kuta Baro',
                    '	Kuta Cot Glie',
                    'Kuta Malaka',
                    '	Lembah Seulawah',
                    '	Leupung',
                    'Lhoknga',
                    'Lhoong',
                    '	Mesjid Raya',
                    '	Montasik',
                    '	Peukan Bada',
                    'Pulo Aceh',
                    '	Seulimeum',
                    'Simpang Tiga',
                    'Suka Makmur',
                ],
                'Kabupaten Aceh Jaya' => [
                    'Teunom',
                    '	Krueng Sabee',
                    'Setia Bhakti',
                    'Sampoiniet',
                    'Jaya',
                    '	Panga',
                    '	Indra Jaya',
                    'Darul Hikmah',
                    '	Pasie Raya',
                ],
                'Kabupaten Aceh Selatan'=>[
                    'Bakongan',
                    'Bakongan Timur',
                    'Kluet Utara',
                    '	Kluet Selatan',
                    'Kluet Tengah',
                    'Kluet Timur',
                    'Kota Bahagia',
                    '	Labuhan Haji',
                    'Labuhan Haji Timur',
                    '	Labuhan Haji Barat',
                    'Meukek',
                    '	Pasie Raja',
                    '	Sama Dua',
                    'Sawang',
                    'Tapak Tuan',
                    '	Trumon',
                    'Trumon Tengah',
                    'Trumon Timur',
                ],
                'Kabupaten Aceh Singkil' => [
                    'Danau Paris',
                    'Gunung Meriah',
                    'Kota Baharu',
                    '	Kuala Baru',
                    '	Pulau Banyak',
                    'Pulau Banyak Barat',
                    'Simpang Kanan',
                    'Singkil',
                    'Singkil Utara',
                    '	Singkohor',
                    'Suro Makmur',
                ],
                'Kabupaten Aceh Tamiang' =>[
                    '	Banda Mulia',
                    '	Bandar Pusaka',
                    '	Bendahara',
                    '	Karang Baru',
                    '	Kejuruan Muda	',
                    'Kota Kuala Simpang',
                    'Manyak Payed',
                    'Rantau',
                    '	Sekerak',
                    '	Seruway',
                    'Tamiang Hulu',
                    'Tenggulun',
                ],
                'Kabupaten Aceh Tengah'=>[
                    'Atu Lintang',
                    'Bebesen',
                    '	Bies',
                    '	Bintang',
                    'Celala',
                    '	Jagong Jeget',
                    '	Kebayakan',
                    'Ketol',
                    '	Kute Panang',
                    '	Laut Tawar',
                    'Linge',
                    'Pegasing',
                    '	Rusip Antara',
                    '	Silih Nara',
                ],
                'Kabupaten Aceh Tenggara'=> [
                    '	Badar',
                    '	Babussalam',
                    'Bambel',
                    'Babul Makmur',
                    '	Babul Rahmah',
                    '	Bukit Tusam',
                    'Darul Hasanah',
                    'Deleng Phokisen',
                    'Ketambe',
                    '	Lawe Alas',
                    '	Lawe Bulan',
                    '	Lawe Sigala-Gala',
                    '	Lawe Sumur',
                    '	Leuser',
                    'Semadam',
                    'Tanah Alas',
                ],
                'Kabupaten Aceh Timur'=>[
                    'Banda Alam',
                    ' Birem Bayeun',
                    '	Darul Aman',
                    'Darul Falah',
                    'Darul Ihsan',
                    'Idi Rayeuk',
                    'Idi Timur',
                    '	Idi Tunong',
                    '	Indra Makmur',
                    '	Julok',
                    '	Madat',
                    '	Nurussalam	',
                    '	Pante Beudari',
                    'Peudawa',
                    '	Peureulak',
                    'Peureulak Timur',
                    'Peureulak Barat',
                    '	Peunaron',
                    '	Ranto Peureulak',
                    '	Rantau Selamat',
                    'Serbajadi',
                    '	Simpang Jernih',
                    'Simpang Ulim',
                    '	Sungai Raya',

                ],
                'Kabupaten Aceh Utara'=>[
                    '	Baktiya',
                    'Baktiya Barat',
                    '	Banda Baro',
                    '	Cot Girek',
                    'Dewantara',
                    'Geureudong Pase',
                    '	Kuta Makmur	',
                    'Langkahan',
                    '	Lapang',
                    '	Lhoksukon',
                    '	Matangkuli',
                    '	Muara Batu',
                    '	Meurah Mulia',
                    '	Nibong',
                    '	Nisam',
                    'Nisam Antara',
                    '	Paya Bakong',
                    '	Pirak Timur',
                    'Samudera',
                    '	Sawang',
                    '	Seunudon',
                    'Simpang Keramat',
                    '	Syamtalira Aron',
                    'Syamtalira Bayu',
                    '	Tanah Jambo Aye',
                    'Tanah Luas',
                    '	Tanah Pasir',
                ],
                'Kabupaten Bener Meriah'=>[
                    '	Bandar',
                    '	Bener Kelipah',
                    '	Bukit',
                    '	Gajah Putih',
                    'Mesidah',
                    '	Permata',
                    '	Pintu Rime Gayo',
                    'Syiah Utama',
                    '	Timang Gajah',
                    '	Wih Pesam',
                ],
                'Kabupaten Bireuen'=>[
                    '	Gandapura',
                    '	Jangka',
                    '	Jeumpa',
                    '	Jeunieb',
                    '	Juli',
                    '	Kota Juang',
                    '	Kuala',
                    'Kuta Blang',
                    '	Makmur',
                    '	Pandrah',
                    'Peudada',
                    '	Peulimbang',
                    '	Peusangan',
                    '	Peusangan Selatan',
                    'Peusangan Siblah Krueng',
                    '	Samalanga',
                    '	Simpang Mamplam',
                ],
                'Kabupaten Gayo Lues'=>[
                    '		Blang Jerango, Gayo Lues',
                    'Blang Kejeren, Gayo Lues',
                    'Blang Pegayon, Gayo Lues',
                    '	Dabun Gelang, Gayo Lues',
                    '	Kuta Panjang, Gayo Lues',
                    'Pantan Cuaca, Gayo Lues',
                    '	Pining, Gayo Lues',
                    '	Putri Betung, Gayo Lues',
                    '	Rikit Gaib, Gayo Lues',
                    '	Terangon, Gayo Lues',
                    '	Tripe Jaya, Gayo Lues',
                ],
                'Kabupaten Nagan Raya'=> [
                    '	Beutong',
                    'Beutong Ateuh Banggalang',
                    'Darul Makmur',
                    '	Kuala',
                    'Kuala Pesisir',
                    '	Seunagan',
                    '	Seunagan Timur',
                    'Suka Makmue',
                    '	Tadu Raya',
                    '	Tripa Makmur',
                ],
                'Kabupaten Pidie' => [
                    'Batee, Pidie',
                    'Delima, Pidie',
                    'Geumpang, Pidie',
                    'Geulumpang Tiga, Pidie',
                    'Keumala, Pidie',
                    'Kota Sigli, Pidie',
                    'Mane, Pidie',
                    'Mila, Pidie',
                    'Muara Tiga, Pidie',
                    'Mutiara, Pidie',
                    'Mutiara Timur, Pidie',
                    'Padang Tiji, Pidie',
                    'Peukan Baro, Pidie',
                    'Pidie, Pidie',
                    'Sakti, Pidie',
                    'Simpang Tiga, Pidie',
                    'Tangse, Pidie',
                    'Tiro, Pidie',
                    'Titeue, Pidie',
                ],
                'Kabupaten Pidie Jaya'=>[
                    'Bandar Baru, Pidie Jaya',
                    'Bandar Dua, Pidie Jaya',
                    'Jangka Buya, Pidie Jaya',
                    'Meurah Dua, Pidie Jaya',
                    'Meureudu, Pidie Jaya',
                    'Panteraja, Pidie Jaya',
                    'Trienggadeng, Pidie Jaya',
                    'Ulim, Pidie Jaya',
                ],
                'Kabupaten Simeulue'=>[
                    'Alafan',
                    'Salang',
                    'Simeulue Barat',
                    'Simeulue Cut',
                    'Simeulue Tengah',
                    'Simeulue Timur',
                    'Teluk Dalam',
                    'Teupah Barat',
                    '	Teupah Selatan',
                    'Teupah Tengah',
                ],
                'Kota Banda Aceh'=>[
                    '	Baiturrahman',
                    'Banda Raya',
                    'Jaya Baru',
                    'Kuta Alam',
                    '	Kuta Raja',
                    'Lueng Bata',
                    'Meuraksa',
                    'Syiah Kuala',
                    'Ulee Kareng',
                ],
                'Kota Langsa'=>[
                    'Langsa Barat',
                    '	Langsa Baro',
                    '	Langsa Kota',
                    '	Langsa Lama',
                    'Langsa Timur',
                ],
                'Kota Lhokseumawe'=>[
                    '	Banda Sakti',
                    '	Blang Mangat',
                    '	Muara Dua',
                    'Muara Satu',
                ],
                'Kota Sabang'=>[
                    'Sukajaya',
                    'Sukakarya',
                ],
                'Kota Subulussalam'=>[
                    'Longkib',
                    'Penanggalan	',
                    '	Rundeng',
                    'Simpang Kiri',
                    '	Sultan Daulat',
                ],
            ],
            'Bali' => [
                'Kabupaten Badung'=>[
                    'Bandar Pasir Mandoge',
                    'Bandar Pulau',
                    '	Aek Songsongan',
                    '	Rahuning',
                    'Pulau Rakyat',
                    'Aek Kuasan',
                    '	Aek Ledong',
                    '	Sei Kepayang',
                    'Sei Kepayang Barat',
                    'Sei Kepayang Timur',
                    'Tanjung Balai',
                    '	Simpang Empat',
                    'Teluk Dalam',
                    '	Air Batu',
                    '	Sei Dadap',
                    'Buntu Pane',
                    '	Tinggi Raja',
                    'Setia Janji',
                    'Meranti',
                    '	Pulo Bandring',
                    '	Rawang Panca Arga',
                    '	Air Joman',
                    'Silau Laut',
                    '	Kota Kisaran Barat',
                    'Kota Kisaran Timur',
                ],
                'Kabupaten Bangli' =>[
                    '	Bangli',
                    'Kintamani',
                    'Susut',
                    '	Tembuku',
                ],
                'Kabupaten Buleleng' => [
                    '	Banjar',
                    '	Buleleng',
                    'Busung Biu',
                    'Gerokgak',
                    '	Kubutambahan',
                    'Sawan  ',
                    '	Seririt',
                    'Sukasada',
                    '	Tejakula',
                ],
                'Kabupaten Gianyar' => [
                    'Blahbatuh',
                    '	Gianyar',
                    'Payangan',
                    '	Sukawati',
                    '	Tampaksiring',
                    '	Tegallalang',
                    '	Ubud',
                ],
                'Kabupaten Jembrana'=>[
                    'Jembrana',
                    'Melaya',
                    'Mendoyo',
                    '	Negara',
                    '	Pekutatan',
                ],
                'Kabupaten Karangasem'=>[
                    '	Abang',
                    '	Bebandem',
                    '	Karangasem',
                    '	Kubu',
                    '	Manggis',
                    '	Rendang',
                    '	Selat',
                    '	Sidemen',
                ],
                'Kabupaten Klungkung'=>[
                    'Banjarangkan',
                    '	Dawan',
                    '	Klungkung',
                    'Nusa Penida',
                ],
                'Kabupaten Tabanan'=>[
                    '	Baturiti',
                    '	Kediri',
                    '	Kerambitan',
                    '	Marga',
                    'Penebel',
                    '	Pupuan',
                    '	Selemadeg',
                    'Selemadeg Barat',
                    'Selemadeg Timur',
                    '	Tabanan',
                ],
                'Kota Denpasar'=>[
                    '	Denpasar Barat',
                    '	Denpasar Selatan',
                    'Denpasar Timur',
                    '	Denpasar Utara',
                ],
            ],
            'Banten' => [
                'Kabupaten Lebak'=>[
                    'Banjarsari',
                    'Bayah',
                    '	Bojongmanik',
                    '	Cibadak',
                    '	Cibeber',
                    'Cigemblong',
                    '	Cihara',
                    'Cijaku',
                    '	Cikulur',
                    '	Cileles',
                    '	Cilograng',
                    '	Cimarga',
                    '	Cipanas',
                    'Cirinten',
                    '	Curugbitung',
                    '	Gunungkencana',
                    '	Kalang Anyar',
                    '	Lebak Gedong',
                    'Leuwidamar',
                    'Maja',
                    '	Malingping',
                    '	Muncang',
                    '	Panggarangan',
                    '	Rangkasbitung',
                    'Sajira',
                    'Sobang',
                    '	Wanasalam',
                    'Warunggunung',
                ],
                'Kabupaten Pandeglang'=>[
                    '	Angsana',
                    '	Banjar',
                    '	Bojong',
                    'Cadasari',
                    'Carita',
                    '	Cibaliung',
                    '	Cibitung',
                    '	Cigeulis',
                    '	Cikedal',
                    '	Cikeusik',
                    'Cimanggu',
                    '	Cimanuk',
                    'Cipeucang',
                    '	Cisata',
                    '	Jiput',
                    '	Kaduhejo',
                    '	Karang Tanjung',
                    'Koroncong',
                    '	Labuan',
                    'Majasari',
                    'Mandalawangi',
                    '	Mekarjaya',
                    '	Menes',
                    'Munjul',
                    '	Pagelaran',
                    '	Pandeglang',
                    '	Panimbang',
                    '	Patia',
                    '	Picung',
                    '	Pulosari',
                    '	Saketi',
                    'Sindangresmi',
                    '	Sobang',
                    '	Sukaresmi',
                    'Sumur',
                ],
                'Kabupaten Serang'=>[
                    '	Anyar',
                    'Bandung',
                    '	Baros',
                    '	Binuang',
                    '	Bojonegara',
                    '	Carenang',
                    '	Cikande',
                    '	Cikeusal',
                    'Cinangka',
                    'Ciomas',
                    '	Ciruas',
                    'Gunung Sari',
                    'Jawilan',
                    '	Kibin',
                    '	Kopo',
                    'Kragilan',
                    '	Kramatwatu',
                    '	Lebak Wangi',
                    '	Mancak',
                    '	Pabuaran',
                    '	Padarincang',
                    '	Pamarayan',
                    '	Petir',
                    'Pontang',
                    'Pulo Ampel',
                    '	Tanara',
                    'Tirtayasa',
                    '	Tunjung Teja',
                    '	Waringinkurung',
                ],
                'Kabupaten Tangerang'=>[
                    'Balaraia',
                    'Cikupa',
                    'Cisauk',
                    'Cisoka',
                    'Curug',
                    'Gunung Kaler',
                    'Jambe',
                    'Jayanti',
                    'Kelapa Dua',
                    'Kemiri',
                    'Kresek',
                    'Kronjo',
                    'Kosambi',
                    'Legok',
                    'Mauk',
                    'Mekarbaru',
                    'Pagedangan',
                    'Pakuhaji',
                    'Panongan',
                    'Pasar Kemis',
                    'Rajeg',
                    'Sepatan',
                    'Sepatan',
                    'Timur',
                    'Sindang Jaya',
                    'Solear',
                    'Sukadiri',
                    'Sukamulya',
                    'Teluknaga',
                    'Tigaraksa',
                ],
                'Kota Cilegon'=>[
                    'Cibeber',
                    '	Cilegon',
                    'Citangkil',
                    'Ciwandan',
                    '	Gerogol',
                    '	Jombang',
                    '	Pulo Merak',
                    '	Purwakarta',
                ],
                'Kota Serang'=>[
                    '	Cipocok Jaya',
                    'Curug',
                    '	Kasemen',
                    '	Serang',
                    'Taktakan',
                    'Walantaka',
                ],
                'Kota Tangerang'=>[
                    'Batuceper',
                    'Benda',
                    'Cibodas',
                    'Ciledug',
                    'Cipondoh',
                    'Jatiuwung',
                    'Karangtengah',
                    'Karawaci',
                    'Larangan',
                    'Neglasari',
                    'Periuk',
                    'Pinang',
                    'Tangerang',
                ],
                'Kota Tangerang selatan'=>[
                    'Ciputat',
                    'Ciputat Timur',
                    'Pamulang',
                    'Pondok Aren',
                    'Serpong',
                    'Setu',
                    'Serpong',
                    'Utara',
                ],
            ],
            'Bengkulu' => [
                'Kabupaten Bengkulu Selatan'=>[
                    '	Kedurang',
                    '	Seginim',
                    '	Pino',
                    '	Manna',
                    '	Kota Manna',
                    'Pino Raya',
                    'Kedurang Ilir',
                    'Air Nipis',
                    'Ulu Manna',
                    '	Bunga Mas',
                    '	Pasar Manna',
                ],
                'Kabupaten Bemgkulu Tengah'=>[
                    'Bang Haji',
                    'Karang Tinggi',
                    '	Merigi Kelindang',
                    '	Merigi Sakti',
                    '	Pagar Jati',
                    '	Pondok Kelapa',
                    '	Pondok Kubang',
                    'Pematang Tiga',
                    '	Semidang Lagan',
                    '	Taba Penanjung',
                    '	Talang Empat',
                ],
                'Kabupaten Bengkulu Utara'=>[
                    'Air Besi, Bengkulu Utara',
                    'Air Napal, Bengkulu Utara',
                    'Air Padang, Bengkulu Utara',
                    'Arma Jaya, Bengkulu Utara',
                    'Batik Nau, Bengkulu Utara',
                    'Enggano, Bengkulu Utara',
                    'Giri Mulya, Bengkulu Utara',
                    'Hulu Palik, Bengkulu Utara',
                    'Kerkap, Bengkulu Utara',
                   ' Ketahun, Bengkulu Utara',
                   ' Kota Arga Makmur, Bengkulu Utara',
                   ' Lais, Bengkulu Utara',
                   ' Marga Sakti Sebelat, Bengkulu Utara',
                   ' Napal Putih, Bengkulu Utara',
                   ' Padang Jaya, Bengkulu Utara',
                   ' Pinang Raya, Bengkulu Utara',
                   ' Putri Hijau, Bengkulu Utara',
                   ' Tanjung Agung Palik, Bengkulu Utara',
                   ' Ulok Kupai, Bengkulu Utara',
                    ],
                'Kabupaten Kaur'=>[
                   ' Kaur Selatan, Kaur',
                   ' Kaur Tengah, Kaur',
                   ' Kaur Utara, Kaur',
                   ' Kelam Tengah, Kaur',
                   ' Kinal, Kaur',
                   ' Lungkang Kule, Kaur',
                   ' Luas, Kaur',
                   ' Maje, Kaur',
                   ' Muara Sahung, Kaur',
                   ' Nasal, Kaur',
                   ' Padang Guci Hilir, Kaur',
                   ' Padang Guci Hulu, Kaur',
                   ' Semidang Gumay, Kaur',
                   ' Tanjung Kemuning, Kaur',
                   ' Tetap, Kaur',
                ],
                'Kabupaten kepahiang'=>[
                   ' Bermani Ilir, Kepahiang',
                   ' Kabawetan, Kepahiang',
                   ' Kepahiang, Kepahiang',
                   ' Merigi, Kepahiang',
                   ' Muara Kemumu, Kepahiang',
                   ' Seberang Musi, Kepahiang',
                   ' Tebat Karai, Kepahiang',
                   ' Ujan Mas, Kepahiang',
                ],
                'Kabupaten Lebong'=>[
                   ' Amen, Lebong',
                   ' Bingin Kuning, Lebong',
                   ' Lebong Atas, Lebong',
                   ' Lebong Utara, Lebong',
                   ' Lebong Sakti, Lebong',
                   ' Lebong Selatan, Lebong',
                   ' Lebong Tengah, Lebong',
                   ' Pelabai, Lebong',
                   ' Pinang Belapis, Lebong',
                   ' Rimbo Pengadang, Lebong',
                   ' Topos, Lebong',
                   ' Uram Jaya, Lebong',
                ],
                'Kabupaten Mukomuko'=>[
                   ' V Koto',
                   ' XIV Koto',
                   ' Air Dikit',
                   ' Air Majunto',
                   ' Air Rami',
                   ' Ipuh',
                   ' Kota',
                   ' Mukomuko',
                   ' Lubuk Pinang',
                   ' Malin Deman',
                   ' Penarik',
                   ' Pondok Suguh',
                   ' Selagan Raya',
                   ' Sungai Rumbai',
                   ' Teramang Jaya',
                    'Teras Terunjam',
                ],
                'Kabupaten Rejang Lebong'=>[
                   ' Bermani Ulu',
                   ' Bermani Ulu Raya',
                   ' Binduriang',
                   ' Curup',
                   ' Curup Selatan',
                   ' Curup Tengah',
                   ' Curup Timur',
                   ' Curup Utara',
                   ' Kota Padang',
                   ' Padang Ulak',
                   ' Tanding',
                   ' Selupu Rejang',
                   ' Sindang Beliti Ulu',
                   ' Sindang Beliti Ilir',
                   ' Sindang Dataran',
                   ' Sindang Kelingi',
                ],
                'Kabupaten seluma'=>[
                   ' Air Periukan',
                   ' llir Talo',
                   ' Lubuk Sandi',
                   ' Sukaraja',
                   ' Seluma',
                   ' Seluma Barat',
                   ' Seluma Selatan',
                   ' Seluma Timur',
                   ' Seluma Utara',
                   ' Semidang Alas',
                    'Maras',
                    'Sukaraia',
                    'Talo',
                    'Talo Kecil',
                    'Ulu Talo',
                ],
                'Kota Bengkulu'=>[
                    'Gading Cempaka',
                    'Kampung Melayu',
                    'Muara Bangka Hulu',
                    'Ratu Agung',
                    'Ratu Samban',
                    'Selebar',
                    'Singaran Pati',
                    'Sungai Serut',
                    'Teluk Segara',
                ],
            ],
            'D.I Yogyakarta' => [
                'Kabupaten Bantul',
                'Kabupaten Gunung kildul',
                'Kabupaten Kulon Progo',
                'Kabupaten Sleman',
                'Kota Yogyakarta',
            ],
            'D.K.I Jakarta' => [
                'Kabupaten Kepulauan Seribu',
                'Kota Jakarta Barat',
                'Kota Jakarta Pusat',
                'Kota Jakarta Selatan',
                'Kota Jakarta Timur',
                'Kota Jakarta Utara',
            ],
            'Gorontalo' => [
                'Kabupaten Boalemo',
                'Kabupaten Bone Bolango',
                'Kabupaten Gorontalo',
                'Kabupaten gorontalo Utara',
                'Kabupaten Pahuwato',
                'Kota Gorontalo',
            ],
            'Jambi' => [
                'Kabupaten Batanghari',
                'Kabupaten Bungo',
                'Kabupaten Kerinci',
                'Kabupaten Merangin',
                'Kabupaten Muaro Jambi',
                'Kabupaten Sarolangun',
                'Kabupaten Tanjung Jabung Barat',
                'Kabupaten Tanjung Jabung Timur',
                'Kabupaten Tebo',
                'Kota Jambi',
                'Kota Sungai Penuh',
            ],
            'Jawa Barat' => [
                'Kabupaten Bandung'=>[
                    'Arjasari',
                    'Baleendah',
                    'Banjaran',
                    'Bojongsoang',
                    'Cangkuang',
                    'Cicalengka',
                    'Cikancung',
                    'Cilengkrang',
                    'Cileunyi',
                    'Cimaung',
                    'Cimenyan',
                    'Ciparay',
                    'Ciwidey',
                    'Dayeuhkolot',
                    'lbun',
                    'Katapang',
                    'Kertasari',
                    'Kutawaringin',
                    'Majalaya',
                    'Margaasih',
                   'Margahayu',
                   'Nagreg',
                   'Pacet',
                   'Pameungpeuk',
                   'Pangalengan',
                   'Paseh',
                   'Pasirjambu',
                   'Rancabali',
                   'Rancaekek',
                   'Solokan Jeruk',
                   'Soreang',
                    ],
                'Kabupaten Bandung Barat'=>[
                    'Batujajar',
                    'Cihampelas',
                    'Cikalong',
                    'Wetan',
                    'Cililin',
                    'Cipatat',
                    'Cipeundeuy',
                    'Cipongkor',
                    'Cisarua',
                    'Gununghalu',
                    'Lembang',
                    'Ngamprah',
                    'Padalarang',
                    'Parongpong',
                    'Rongga',
                    'Saguling',
                    'Sindangkerta',
                ],
                'Kabupaten Bekasi'=>[
                    'Babelan',
                    'Bojongmangu',
                    'Cabangbungin',
                    'Cibarusah',
                    'Cibitung',
                    'Cikarang Barat',
                    'Cikarang Pusat',
                    'Cikarang',
                    'Selatan',
                    'Cikarang Timur',
                    'Cikarang Utara',
                    'Karangbahagia',
                    'Kedungwaringin',
                    'Muara Gembong',
                    'Pebayuran',
                    'Serang Baru',
                    'Setu',
                    'Sukakarya',
                    'Sukatani',
                    'Sukawangi',
                    'Tambelang',
                    'Tambun Selatan',
                    'Tambun Utara',
                    'Tarumajaya',
                ],
                'Kabupaten Bogor'=>[
                    'Babakan Madang',
                    'Bojonggede',
                    'Caringin',
                    'Cariu',
                    'Ciampea',
                    'Ciawi',
                    'Cibinong',
                    'Cibungbulang',
                    'Cigombong',
                    'Cigudeg',
                    'Cijeruk',
                    'Cileungsi',
                    'Ciomas',
                    'Cisarua',
                    'Ciseeng',
                    'Citeureup',
                    'Dramaga',
                    'Gunung Putri',
                    'Gunung Sindur',
                    'Jasinga',
                    'Jonggol',
                    'Kemang',
                    'Klapanunggal',
                    'Leuwiliang',
                    'Leuwisadeng',
                    'Megamendung',
                    'Nanggung',
                    'Pamijahan',
                    'Parung',
                    'Parung Panjang',
                    'Ranca Bungur',
                    'Rumpin',
                    'Sukajaya',
                    'Sukamakmur',
                    'Sukaraja',
                    'Tajur Halang',
                    'Tamansari',
                    'Tanjungsari',
                    'Tenjo',
                    'Tenjolaya',
                ],
                'Kabupaten Ciamis'=>[
                    'Banjaranyar',
                    'Banjarsari',
                    'Baregbeg',
                    'Ciamis',
                    'Cidolog',
                    'Cihaurbeuti',
                    'Cijeungjing',
                    'Cikoneng',
                    'Cimaragas',
                    'Cipaku',
                    'Cisaga',
                    'Jatinagara',
                    'Kawali',
                    'Lakbok',
                    'Lumbung',
                    'Pamarican',
                    'Panjalu',
                    'Panawangan',
                    'Panumbangan',
                    'Purwadadi',
                    'Rajadesa',
                    'Rancah',
                    'Sadananya',
                    'Sindangkasih',
                    'Sukadana',
                    'Sukamantri',
                    'Tambaksari',
                ],
                'Kabupaten Cianjur'=>[
                    'Naringgul',
                    'Agrabinta',
                    'Bojongpicung',
                    'Campaka',
                    'Campaka Mulya',
                    'Cianjur',
                    'Cibeber',
                    'Cibinong',
                    'Cidaun',
                    'Cijati',
                    'Cikadu',
                    'Cikalongkulon',
                    'Cilaku',
                    'Cipanas',
                    'Ciranjang',
                    'Cugenang',
                    'Gekbrong',
                    'Haurwangi',
                    'Kadupandak',
                    'Karangtengah',
                    'Leles',
                    'Mande',
                    'Pacet',
                    'Pagelaran',
                    'Pasirkuda',
                    'Sindangbarang',
                    'Sukaluyu',
                    'Sukanagara',
                    'Sukaresmi',
                    'Takokak',
                    'Tanggeung',
                    'Warungkondang',
                ],
                'Kabupaten Cirebon'=>[
                    'Arjawinangun',
                    'Astanajapura',
                    'Babakan',
                    'Beber',
                    'Ciledug',
                    'Ciwaringin',
                    'Depok',
                    'Dukupuntang',
                    'Gebang',
                    'Gegesik',
                    'Gempol',
                    'Greged',
                    'Gunungjati',
                    'Jamblang',
                    'Kaliwedi',
                    'Kapetakan',
                    'Karangsembung',
                    'Karangwareng',
                    'Kedawung',
                    'Klangenan',
                    'Lemahabang',
                    'Losari',
                    'Mundu',
                    'Pabedilan',
                    'Pabuaran',
                    'Palimanan',
                    'Pangenan',
                    'Panguragan',
                    'Pasaleman',
                    'Plered',
                    'Plumbon',
                    'Sedong',
                    'Sumber',
                    'Suranenggala',
                    'Susukan',
                    'Susukanlebak',
                    'Talun',
                    'Tengahtani',
                    'Waled',
                    'Weru',
                ],
                'Kabupaten Garut'=>[
                    'Banjarwangi',
                    'Banyuresmi',
                    'Bayongbong',
                    'Balubur',
                    'Limbangan',
                    'Bungbulang',
                    'Caringin',
                    'Cibalong',
                    'Cibatu',
                    'Cibiuk',
                    'Cigedug',
                    'Cihurip',
                    'Cikajang',
                    'Cikelet',
                    'Cilawu',
                    'Cisewu',
                    'Cisompet',
                    'Cisurupan',
                    'Garut Kota',
                    'Kadungora',
                    'Karangpawitan',
                    'Karangtengah',
                    'Kersamanah',
                    'Leles',
                    'Leuwigoong',
                    'Malangbong',
                    'Mekarmukti',
                    'Pakenjeng',
                    'Pameungpeuk',
                    'Pamulihan',
                    'Pangatikan',
                    'Pasirwangi',
                    'Peundeuy',
                    'Samarang',
                    'Selaawi',
                    'Singajaya',
                    'Sucinaraja',
                    'Sukaresmi',
                    'Sukawening',
                    'Talegong',
                    'Tarogong Kaler',
                    'Tarogong Kidul',
                    'Wanaraja',
                ],
                'Kabupaten Indramayu'=>[
                    'Anjatan',
                    'Arahan',
                    'Balongan',
                    'Bangodua',
                    'Bongas',
                    'Cantigi',
                    'Cikedung',
                    'Gabuswetan',
                    'Gantar',
                    'Haurgeulis',
                    'Indramayu',
                    'Jatibarang',
                    'Juntinyuat',
                    'Kandanghaur',
                    'Karangampel',
                    'Kedokan',
                    'Bunder',
                    'Kertasemaya',
                    'Krangkeng',
                    'Kroya',
                    'Lelea',
                    'Lohbener',
                    'Pasekan',
                    'Losarang',
                    'Pasekan',
                    'Patrol',
                    'Sindang',
                    'Sliyeg',
                    'Sukagumiwang',
                    'Sukra',
                    'Terisi',
                    'Tukdana',
                    'Widasari',
                ],
                'Kabupaten Karawang'=>[
                    'Banyusari',
                    'Batujaya',
                    'Ciampel',
                    'Cibuaya',
                    'Cikampek',
                    'Cilamaya Kulon',
                    'Cilamaya Wetan',
                    'Cilebar',
                    'Jatisari',
                    'Jayakerta',
                    'Karawang Barat',
                    'Karawang Timur',
                    'Klari',
                    'Kotabaru',
                    'Kutawaluya',
                    'Lemahabang',
                    'Majalaya',
                    'Pakisjaya',
                    'Pangkalan',
                    'Pedes',
                    'Purwasari',
                    'Rawamerta',
                    'Rengasdengklok',
                    'Tegalwaru',
                    'Talagasari',
                    'Telukjambe',
                    'Barat',
                    'Telukjambe',
                    'Timur',
                    'Tempuran',
                    'Tirtajaya',
                    'Tirtamulya',
                ],
                'Kabupaten Kuningan'=>[
                    'Ciawigebang',
                    'Cibeureum',
                    'Cibingbin',
                    'Cidahu',
                    'Cigandamekar',
                    'Cigugur',
                    'Cilebak',
                    'Cilimus',
                    'Cimahi',
                    'Ciniru',
                    'Cipicung',
                    'Ciwaru',
                    'Darma',
                    'Garawangi',
                    'Hantara',
                    'Jalaksana',
                    'Japara',
                    'Kadugede',
                    'Kalimanggis',
                    'Karangkancana',
                    'Kramatmulya',
                    'Kuningan',
                    'Lebakwangi',
                    'Luragung',
                    'Maleber',
                    'Mandirancan',
                    'Nusaherang',
                    'Pancalang',
                    'Pasawahan',
                    'Selajambe',
                    'Sindangagung',
                    'Subang',
                ],
                'Kabupaten Majalengka'=>[
                    'Argapura',
                    'Banjaran',
                    'Bantarujeg',
                    'Cigasong',
                    'Cikijing',
                    'Cingambul',
                    'Dawuan',
                    'Jatitujuh',
                    'Jatiwangi',
                    'Kadipaten',
                    'Kasokandel',
                    'Kertajati',
                    'Lemahsugih',
                    'Leuwimunding',
                    'Ligung',
                    'Maja',
                    'Majalengka',
                    'Malausma',
                    'Palasah',
                    'Panyingkiran',
                    'Rajagaluh',
                    'Sindang',
                    'Sindangwangi',
                    'Sukahaji',
                    'Sumberjaya',
                    'Talaga',
                ],
                'Kabupaten Pangandaran'=>[
                    'Cigugur',
                    'Cijulang',
                    'Cimerak',
                    'Kalipucang',
                    'Langkaplancar',
                    'Mangunjaya',
                    'Padaherang',
                    'Pangandaran',
                    'Parigi',
                    'Sidamulih',
                ],
                'Kabupaten Purwakarta'=>[
                    'Babakancikao',
                    'Bojong',
                    'Bungursari',
                    'Campaka',
                    'Cibatu',
                    'Darangdan',
                    'Jatiluhur',
                    'Kiarapedes',
                    'Maniis',
                    'Pasawahan',
                    'Plered',
                    'Pondoksalam',
                    'Purwakarta',
                    'Sukasari',
                    'Sukatani',
                    'Tegalwaru',
                    'Wanayasa',
                ],
                'Kabupaten Subang'=>[
                    'Binong',
                    'Blanakan',
                    'Ciasem',
                    'Ciater',
                    'Cibogo',
                    'Cijambe',
                    'Cikaum',
                    'Cipeundeuy',
                    'Cipunagara',
                    'Cisalak',
                    'Compreng',
                    'Dawuan',
                    'Jalan Cagak',
                    'Kalijati',
                    'Kasomalang',
                    'Legon Kulon',
                    'Pabuaran',
                    'Pagaden',
                    'Pagaden Barat',
                    'Pamanukan',
                    'Patok Beusi',
                    'Purwadadi',
                    'Pusakajaya',
                    'Pusakanagara',
                    'Sagalaherang',
                    'Serangpanjang',
                    'Subang',
                    'Sukasari',
                    'Tambakdahan',
                    'Tanjung Siang',
                ],
                'Kabupaten Sukabumi'=>[
                    'Bantargadung',
                    'Bojong Genteng',
                    'Caringin',
                    'Ciambar',
                    'Cibadak',
                    'Cibitung',
                    'Cicantayan',
                    'Cicurug',
                    'Cidadap',
                    'Cidolog',
                    'Cidahu',
                    'Ciemas',
                    'Cikakak',
                    'Cikembar',
                    'Cikidang',
                    'Cimanggu',
                    'Ciracap',
                    'Cireunghas',
                    'Cisaat',
                    'Cisolok',
                    'Curugkembar',
                    'Gegerbitung',
                    'Gunung Guruh',
                    'Jampang Kulon',
                    'Jampang Tengah',
                    'Kabandungan',
                    'Kadudampit',
                    'Kalapanunggal',
                    'Kalibunder',
                    'Kebonpedes',
                    'Lengkong',
                    'Nagrak',
                    'Nyalindung',
                    'Pabuaran',
                    'Palabuhanratu',
                    'Parakansalak',
                    'Parungkuda',
                    'Purabaya',
                    'Sagaranten',
                    'Simpenan',
                    'Sukabumi',
                    'Sukalarang',
                    'Sukaraia',
                    'Surade',
                    'Tegal Buleud',
                    'Waluran',
                    'Warung Kiara',
                ],
                'Kabupaten Sumedang'=>[
                    'Buahdua',
                    'Cibugel',
                    'Cimalaka',
                    'Cimanggung',
                    'Cisarua',
                    'Cisitu',
                    'Conggeang',
                    'Darmaraja',
                    'Ganeas',
                    'Jatigede',
                    'Jatinangor',
                    'Jatinunggal',
                    'Pamulihan',
                    'Paseh',
                    'Rancakalong',
                    'Situraja',
                    'Sukasari',
                    'Sumedang',
                    'Selatan',
                    'Sumedang Utara',
                    'Surian',
                    'Tanjungkerta',
                    'Tanjungmedar',
                    'Tanjungsari',
                    'Tomo',
                    'Wado',
                    'Ujung Jaya',
                ],
                'Kabupaten Tasikmalaya'=>[
                    'Bantarkalong',
                    'Bojongasih',
                    'Bojonggambir',
                    'Ciawi',
                    'Cibalong',
                    'Cigalontang',
                    'Cikalong',
                    'Cikatomas',
                    'Cineam',
                    'Cipatujah',
                    'Cisayong',
                    'Culamega',
                    'Gunung Tanjung',
                    'Jamanis',
                    'Jatiwaras',
                    'Kadipaten',
                    'Karang Jaya',
                    'Karangnunggal',
                    'Leuwisari',
                    'Mangunreja',
                    'Manonjaya',
                    'Padakembang',
                    'Pagerageung',
                    'Pancatengah',
                    'Parungponteng',
                    'Puspahiang',
                    'Rajapolah',
                    'Salawu',
                    'Salopa',
                    'Sariwangi',
                    'Singaparna',
                    'Sodonghilir',
                    'Sukahening',
                    'Sukaraja',
                    'Sukarame',
                    'Sukaratu',
                    'Sukaresik',
                    'Tanjungjaya',
                    'Taraju',
                ],
                'Kota Bandung'=>[
                    'Andir',
                    'Astana Anyar',
                    'Antapani',
                    'Arcamanik',
                    'Babakan Ciparay',
                    'Bandung Kidul',
                    'Bandung Kulon',
                    'Bandung Wetan',
                    'Batununggal',
                    'Bojongloa Kaler',
                    'Bojongloa Kidul',
                    'Buahbatu',
                    'Cibeunying Kaler',
                    'Cibeunying Kidul',
                    'Cibiru',
                    'Cicendo',
                    'Cidadap',
                    'Cinambo',
                    'Coblong',
                    'Gedebage',
                    'Kiaracondong',
                    'Lengkong',
                    'Mandalajati',
                    'Panyileukan',
                    'Rancasari',
                    'Regol',
                    'Sukajadi',
                    'Sukasari',
                    'Sumur Bandung',
                    'Ujungberung',
                ],
                'Kota Banjar'=>[
                    'Banjar',
                    'Langensari',
                    'Pataruman',
                    'Purwaharja',
                ],
                'Kota Bekasi'=>[
                    'Bantar Gebang',
                    'Bekasi Barat',
                    'Bekasi Selatan',
                    'Bekasi Timur',
                    'Bekasi Utara',
                    'Jatiasih',
                    'Jatisampurna',
                    'Medan Satria',
                    'Mustika Jaya',
                    'Pondok Gede',
                    'Pondok Melati',
                    'Rawalumbu',
                ],
                'Kota Bogor'=>[
                    'Bogor Barat',
                    '	Bogor Selatan',
                    'Bogor Tengah',
                    'Bogor Timur',
                    '	Bogor Utara',
                    'Tanah Sareal',
                ],
                'Kota Cimahi'=>[

                ],
                'Kota Cirebon',
                'Kota Depok',
                'Kota Sukabumi',
                'Kota Tasikmalaya',
            ],
            'Jawa Tengah' => [
                'Kabupaten Banjarnegara',
                'Kabupaten Banyumas',
                'Kabupaten Batang',
                'Kabupaten Blora',
                'Kabupaten Boyolali',
                'Kabupaten Brebes',
                'Kabupaten Cilacap',
                'Kabupaten Demak',
                'Kabupaten Grobogan',
                'Kabupaten Jepara',
                'Kabupaten Karanganyar',
                'Kabupaten Kebumen',
                'Kabupaten Kendal',
                'Kabupaten Klaten',
                'Kabupaten Kudus',
                'Kabupaten Magelang',
                'Kabupaten Pati',
                'Kabupaten Pekalongan',
                'Kabupaten Pemalang',
                'Kabupaten Purbalingga',
                'Kabupaten Purworejo',
                'Kabupaten Rembang',
                'Kabupaten Semarang',
                'Kabupaten Sragen',
                'Kabupaten Sukoharjo',
                'Kabupaten Tegal',
                'Kabupaten Temanggung',
                'Kabupaten Wonogiri',
                'Kabupaten Wonosobo',
                'Kota Magelang',
                'Kota Pekalongan',
                'Kota Salatiga',
                'Kota Semarang',
                'Kota Surakarta',
                'Kota Tegal',
            ],
            'Jawa Timur' => [
                'Kabupaten Bangkalan',
                'Kabupaten Banyuwangi',
                'Kabupaten Blitar',
                'Kabupaten Bojonegoro',
                'Kabupaten Bondowoso',
                'Kabupaten Gresik',
                'Kabupaten Jember',
                'Kabupaten Jombang',
                'Kabupaten Kediri',
                'Kabupaten Lamongan',
                'Kabupaten Lumajang',
                'Kabupaten Madiun',
                'Kabupaten Magetan',
                'Kabupaten Malang',
                'Kabupaten Mojokerto',
                'Kabupaten Nganjuk',
                'Kabupaten Ngawi',
                'Kabupaten Pacitan',
                'Kabupaten Pamekasan',
                'Kabupaten Pasuruan',
                'Kabupaten Ponorogo',
                'Kabupaten Probolinggo',
                'Kabupaten Sampang',
                'Kabupaten Sidoarjo',
                'Kabupaten Situbondo',
                'Kabupaten Sumenep',
                'Kabupaten Trenggalek',
                'Kabupaten Tuban',
                'Kabupaten Tulungagung',
                'Kota Batu',
                'Kota Blitar',
                'Kota Kediri',
                'Kota Madiun',
                'Kota Malang',
                'Kota Mojokerto',
                'Kota Pasuruan',
                'Kota Probolinggo',
                'Kota Surabaya',
            ],
            'Kalimantan Barat' => [
                'Kabupaten Bengkayang',
                'Kabupaten Kapuas Hulu',
                'Kabupaten Kayong Utara',
                'Kabupaten Ketapang',
                'Kabupaten Kubu Raya',
                'Kabupaten Landak',
                'Kabupaten Melawi',
                'Kabupaten Pontianak',
                'Kabupaten Sambas',
                'Kabupaten Sanggau',
                'Kabupaten Sekadau',
                'Kabupaten Sintang',
                'Kota Pontianak',
                'Kota Singkawang',
            ],
            'Kalimantan Selatan' => [
                'Kabupaten Balangan',
                'Kabupaten Banjar',
                'Kabupaten Barito Kuala',
                'Kabupaten Hulu Sungai Selatan',
                'Kabupaten Hulu Sungai Tengah',
                'Kabupaten Hulu Sungai Utara',
                'Kabupaten Kotabaru',
                'Kabupaten Tabalong',
                'Kabupaten Tanah Bumbu',
                'Kabupaten Tanah Laut',
                'Kabupaten Tapin',
                'Kota Banjarbaru',
                'Kota Banjarmasin',
            ],
            'Kalimantan Tengah' => [
                'Kabupaten Barito Selatan',
                'Kabupaten Barito Timur',
                'Kabupaten Barito Utara',
                'Kabupaten Gunung Mas',
                'Kabupaten Kapuas',
                'Kabupaten Katingan',
                'Kabupaten Kotawaringin Barat',
                'Kabupaten Kotawaringin Timur',
                'Kabupaten Lamandau',
                'Kabupaten Murung Raya',
                'Kabupaten Pulang Pisau',
                'Kabupaten Sukamara',
                'Kabupaten Seruyan',
                'Kota Palangka Raya',
            ],
            'Kalimantan Timur' => [
                'Kabupaten Berau',
                'Kabupaten Kutai Barat',
                'Kabupaten Kutai Kartanegara',
                'Kabupaten Kutai Timur',
                'Kabupaten Paser',
                'Kabupaten Penajam Paser Utara',
                'Kabupaten Mahakam Ulu',
                'Kota Balikpapan',
                'Kota Bontang',
                'Kota Samarinda',
            ],
            'Kalimantan Utara' => [
                'Kabupaten Bulungan',
                'Kabupaten Malinau',
                'Kabupaten Nunukan',
                'Kabupaten Tana Tidung',
                'Kota Tarakan',
            ],
            'Kepulauan Bangka Belitung' => [
                'Kabupaten Bangka',
                'Kabupaten Bangka Barat',
                'Kabupaten Bangka Selatan',
                'Kabupaten Bangka Tengah',
                'Kabupaten Belitung',
                'Kabupaten Belitung Timur',
                'Kota Pangkal Pinang',
            ],
            'Kepulauan Riau' => [
                'Kabupaten Bintan'=>[
                    'Bintan Pesisir',
                    'Bintan Timur',
                    'Bintan Utara',
                    'Gunung Kijang',
                    'Mantang',
                    'Seri Kuala Lobam',
                    'Tambelan',
                    'Teluk Sebong',
                    'Teluk Bintan',
                    'Toapaya',
                ],
                'Kabupaten Karimun'=>[
                    'Belat',
                    'Buru',
                    'Durai',
                    'Karimun',
                    'Kundur',
                    'Kundur Barat',
                    'Kundur Utara',
                    'Meral',
                    'Meral Barat',
                    'Moro',
                    'Tebing',
                    'Ungar',
                ],
                'Kabupaten Kepulauan Anambas'=>[
                    'Jemaja',
                    'Jemaja Timur',
                    'Palmatak',
                    'Siantan',
                    'Siantan Selatan',
                    'Siantan Tengah',
                    'Siantan Timur',
                ],
                'Kabupaten Lingga'=>[
                    'Bakung Serumpun',
                    'Katang Bidare',
                    'Kepulauan Posek',
                    'Lingga',
                    'Lingga Timur',
                    'Lingga Utara',
                    'Selayar',
                    'Senayang',
                    'Singkep',
                    'Singkep Barat',
                    'Singkep Pesisir',
                    'Singkep Selatan',
                    'Temiang Pesisir',
                ],
                'Kabupaten Natuna'=>[
                    'Bunguran Barat',
                    'Bunguran Batubi',
                    'Bunguran Selatan',
                    'Bunguran Tengah',
                    'Bunguran Timur',
                    'Bunguran Timur Laut',
                    'Bunguran Utara',
                    'Midai',
                    'Pulau Laut',
                    'Pulau Tiga',
                    'Pulau Tiga Barat',
                    'Serasan',
                    'Serasan Timur',
                    'Suak Midai',
                    'Subi',
                    'Teluk Buton',
                ],
                'Kota Batam'=>[
                    'Batam Kota',
                    'Batu Aji',
                    'Batu Ampar',
                    'Belakang Padang',
                    'Bengkong',
                    'Bulang',
                    'Galang',
                    'Lubuk Baja',
                    'Nongsa',
                    'Sagulung',
                    'Sei Beduk',
                    'Sekupang',
                ],
                'Kota Tanjung Pinang'=>[
                    'Bukit Bestari',
                    'Tanjung Pinang Barat',
                    'Tanjung Pinang Kota',
                    'Tanjung Pinang Timur',
                ],
            ],
            'Lampung' => [
                'Kabupaten Lampung Barat',
                'Kabupaten Lampung Selatan',
                'Kabupaten Lampung Tengah',
                'Kabupaten Lampung Timur',
                'Kabupaten Lampung Utara',
                'Kabupaten Mesuji',
                'Kabupaten Pesawaran',
                'Kabupaten Pringsewu',
                'Kabupaten Tanggamus',
                'Kabupaten Tulang Bawang',
                'Kabupaten Tulang Bawang Barat',
                'Kabupaten Way Kanan',
                'Kabupaten Pesisir Barat',
                'Kota Bandar Lampung',
                'Kota Kotabumi',
                'Kota Liwa',
                'Kota Metro',
            ],
            'Maluku' => [
                'Kabupaten Buru',
                'Kabupaten Buru Selatan',
                'Kabupaten Kepulauan Aru',
                'Kabupaten Maluku Barat Daya',
                'Kabupaten Maluku Tengah',
                'Kabupaten Maluku Tenggara',
                'Kabupaten Maluku Tenggara Barat',
                'Kabupaten Seram Bagian Barat',
                'Kabupaten Seram Bagian Timur',
                'Kota Ambon',
                'Kota Tual',
            ],
            'Maluku Utara' => [
                'Kabupaten Halmahera Barat',
                'Kabupaten Halmahera Tengah',
                'Kabupaten Halmahera Utara',
                'Kabupaten Halmahera Selatan',
                'Kabupaten Halmahera Timur',
                'Kabupaten Kepulauan Sula',
                'Kabupaten Pulau Morotai',
                'Kabupaten Pulau Taliabu',
                'Kota Ternate',
                'Kota Tidore Kepulauan',
            ],
            'Nusa Tenggara Barat' => [
                'Kabupaten Bima',
                'Kabupaten Dompu',
                'Kabupaten Lombok Barat',
                'Kabupaten Lombok Tengah',
                'Kabupaten Lombok Timur',
                'Kabupaten Lombok Utara',
                'Kabupaten Sumbawa',
                'Kabupaten Sumbawa Barat',
                'Kota Bima',
                'Kota Mataram',
            ],
            'Nusa Tenggara Timur' => [
                'Kabupaten Alor',
                'Kabupaten Belu',
                'Kabupaten Ende',
                'Kabupaten Flores Timur',
                'Kabupaten Kupang',
                'Kabupaten Lembata',
                'Kabupaten Manggarai',
                'Kabupaten Manggarai Barat',
                'Kabupaten Manggarai Timur',
                'Kabupaten Ngada',
                'Kabupaten Nagekeo',
                'Kabupaten Rote Ndao',
                'Kabupaten Sabu Raijua',
                'Kabupaten Sikka',
                'Kabupaten Sumba Barat',
                'Kabupaten Sumba Barat Daya',
                'Kabupaten Sumba Tengah',
                'Kabupaten Sumba Timur',
                'Kabupaten Timor Tengah Selatan',
                'Kabupaten Timor Tengah Utara',
                'Kota Kupang',
            ],
            'Papua' => [
                'Kabupaten Asmat',
                'Kabupaten Biak Numfor',
                'Kabupaten Boven Digoel',
                'Kabupaten Deiyai',
                'Kabupaten Dogiyai',
                'Kabupaten Intan Jaya',
                'Kabupaten Jayapura',
                'Kabupaten Jayawijaya',
                'Kabupaten Keerom',
                'Kabupaten Kepulauan Yapen',
                'Kabupaten Lanny Jaya',
                'Kabupaten Mamberamo Raya',
                'Kabupaten Mamberamo Tengah',
                'Kabupaten Mappi',
                'Kabupaten Merauke',
                'Kabupaten Mimika',
                'Kabupaten Nabire',
                'Kabupaten Nduga',
                'Kabupaten Paniai',
                'Kabupaten Pegunungan Bintang',
                'Kabupaten Puncak',
                'Kabupaten Puncak Jaya',
                'Kabupaten Sarmi',
                'Kabupaten Supiori',
                'Kabupaten Tolikara',
                'Kabupaten Waropen',
                'Kabupaten Yahukimo',
                'Kabupaten Yalimo',
                'Kota Jayapura',
            ],
            'Papua Barat' => [
                'Kabupaten Fakfak'=> ['
                '],
                'Kabupaten Kaimana',
                'Kabupaten Manokwari',
                'Kabupaten Manokwari Selatan',
                'Kabupaten Maybrat',
                'Kabupaten Pegunungan Arfak',
                'Kabupaten Raja Ampat',
                'Kabupaten Sorong',
                'Kabupaten Sorong Selatan',
                'Kabupaten Tambrauw',
                'Kabupaten Teluk Bintuni',
                'Kabupaten Teluk Wondama',
                'Kota Sorong',
            ],
            'Riau' => [
                'Kabupaten Bengkalis'=>[
                    'Bengkalis',
                    'Bantan',
                    'Bukit Batu',
                    'Mandau',
                    'Rupat',
                    'Rupat Utara',
                    'Siak Kecil',
                    'Pinggir',
                    'Bandar Laksamana',
                    'Talang Muandau',
                ],
                'Kabupaten Indragiri Hilir'=>[
                    'Batang Tuaka',
                    'Concong',
                    'Enok',
                    'Gaung',
                    'Gaung Anak Serka',
                    'Kateman',
                    'Kempas',
                    'Kemuning',
                    'Keritang',
                    'Kuala Indragiri',
                    'Mandah',
                    'Pelangiran',
                    'Pulau Burung',
                    'Reteh',
                    'Sungai Batang',
                    'Tanah Merah',
                    'Teluk Belengkong',
                    'Tembilahan',
                    'Tembilahan Hulu',
                    'Tempuling',
                ],
                'Kabupaten Indragiri Hulu'=>[
                    'Batang Cenaku',
                    'Batang Gangsal',
                    'Batang Peranap',
                    'Lirik',
                    'Lubuk Batu Jaya',
                    'Kelayang',
                    'Kuala Cenaku',
                    'Peranap',
                    'Rakit Kulim',
                    'Rengat',
                    'Rengat Barat',
                    'Siberida',
                    'Sungai Lala',
                ],
                'Kabupaten Kampar'=>[
                    'XIII Koto Kampar',
                    'Bangkinang',
                    'Bangkinang Kota',
                    'Gunung Sahilan',
                    'Kampa',
                    'Kampar',
                    'Kampar Kiri',
                    'Kampar Kiri Hilir',
                    'Kampar Kiri Hulu',
                    'Kampar Kiri Tengah',
                    'Kampar Utara',
                    'Koto Kampar Hulu',
                    'Kuok',
                    'Perhentian Raja',
                    'Rumbio Jaya',
                    'Salo',
                    'Siak Hulu',
                    'Tambang',
                    'Tapung',
                    'Tapung Hilir',
                    'Tapung Hulu',
                ],
                'Kabupaten Kepulauan Meranti'=>[
                    'Merbau',
                    'Pulau Merbau',
                    'Rangsang',
                    'Rangsang Barat',
                    'Rangsang Pesisir',
                    'Tasik Putri Puyu',
                    'Tebing Tinggi',
                    'Tebing Tinggi Barat',
                    'Tebing Tinggi Timur',

                ],
                'Kabupaten Kuantan Singingi'=>[
                    'Benai',
                    'Cerenti',
                    'Gunung Toar',
                    'Inuman',
                    'Hulu Kuantan',
                    'Kuantan Hilir',
                    'Kuantan Hilir Seberang',
                    'Kuantan Mudik',
                    'Kuantan Tengah',
                    'Logas Tanah Darat',
                    'Pangean',
                    'Pucuk Rantau',
                    'Sentajo Raya',
                    'Singingi',
                    'Singingi Hilir',
                ],
                'Kabupaten Pelalawan'=>[
                    'Bandar Petalangan',
                    'Bandar Sei Kijang',
                    'Bunut',
                    'Kerumutan',
                    'Kuala Kampar',
                    'Langgam',
                    'Pangkalan Kerinci',
                    'Pangkalan Kuras',
                    'Pangkalan Lesung',
                    'Pelalawan',
                    'Teluk Meranti',
                    'Ukui',
                ],
                'Kabupaten Rokan Hilir'=>[
                    'Bagan Sinembah',
                    'Bagan Sinembah Raya',
                    'Balai Jaya',
                    'Bangko',
                    'Bangko Pusoko',
                    'Batu Hampar',
                    'Kubu',
                    'Kubu Babussalam',
                    'Pasir Limau Kapas',
                    'Pekaitan',
                    'Pujud',
                    'Rantau Kopar',
                    'Rimba Melintang',
                    'Simpang Kanan',
                    'Sinaboi',
                    'Tanah Putih',
                    'Tanah Putih Tanjung Melawan',
                    'Tanjung Medan',
                ],
                'Kabupaten Rokan Hulu'=>[
                    'Bangun Purba',
                    'Bonai Darussalam',
                    'Kabun',
                    'Kepenuhan',
                    'Kepenuhan Hulu',
                    'Kunto Darussalam',
                    'Pagaran Tapah Darussalam',
                    'Pendalian IV Koto',
                    'Rambah',
                    'Rambah Hilir',
                    'Rambah Samo',
                    'Rokan IV Koto',
                    'Tambusai',
                    'Tambusai Utara',
                    'Tandun',
                    'Ujung Batu',
                ],
                'Kabupaten Siak'=>[
                    'Bunga Raya',
                    'Dayun',
                    'Kandis',
                    'Kerinci Kanan',
                    'Kota Gasip',
                    'Lubuk Dalam',
                    'Mempura',
                    'Minas',
                    'Pusako',
                    'Sabak Auh',
                    'Siak',
                    'Sungai Apit',
                    'Sungai Mandau',
                    'Tualang',

                ],
                'Kota Dumai'=>[
                    'Bukit Kapur',
                    'Dumai Barat',
                    'Dumai Kota',
                    'Dumai Selatan',
                    'Dumai Timur',
                    'Medang Kampai',
                    'Sungai Sembilan',

                ],
                'Kota Pekanbaru'=>[
                    'Bukit Raya',
                    'Lima Puluh',
                    'Marpoyan Damai',
                    'Payung Sekaki',
                    'Pekanbaru Kota',
                    'Rumbai Barat',
                    'Rumbai ',
                    'Rumbai Timur',
                    'Sail',
                    'Senapelan',
                    'Sukajadi',
                    'Bina Widya',
                    'Tuah Madani',
                    'Tenayan Raya',
                    'Kulim',
                ],
            ],
            'Sulawesi Barat' => [
                'Kabupaten Majene',
                'Kabupaten Mamasa',
                'Kabupaten Mamuju',
                'Kabupaten Mamuju Utara',
                'Kabupaten Polewali Mandar',
                'Kabupaten Mamuju Tengah',
            ],
            'Sulawesi Selatan' => [
                'Kabupaten Bantaeng',
                'Kabupaten Barru',
                'Kabupaten Bone	Watampone',
                'Kabupaten Bulukumba',
                'Kabupaten Enrekang',
                'Kabupaten Gowa',
                'Kabupaten Jeneponto',
                'Kabupaten Kepulauan Selayar',
                'Kabupaten Luwu',
                'Kabupaten Luwu Timur',
                'Kabupaten Luwu Utara',
                'Kabupaten Maros',
                'Kabupaten Pangkajene dan Kepulauan',
                'Kabupaten Pinrang',
                'Kabupaten Sidenreng Rappang',
                'Kabupaten Sinjai',
                'Kabupaten Soppeng',
                'Kabupaten Takalar',
                'Kabupaten Tana Toraja',
                'Kabupaten Toraja Utara',
                'Kabupaten Wajo',
                'Kota Makassar',
                'Kota Palopo',
                'Kota Parepare',
            ],
            'Sulawesi Tengah' => [
                'Kabupaten Banggai',
                'Kabupaten Banggai Kepulauan',
                'Kabupaten Banggai Laut',
                'Kabupaten Buol',
                'Kabupaten Donggala',
                'Kabupaten Morowali',
                'Kabupaten Parigi Moutong',
                'Kabupaten Poso',
                'Kabupaten Sigi',
                'Kabupaten Tojo Una-Una',
                'Kabupaten Tolitoli',
                'Kota Palu',
            ],
            'Sulawesi Tenggara' => [
                'Kabupaten Bombana',
                'Kabupaten Buton',
                'Kabupaten Buton Utara',
                'Kabupaten Kolaka',
                'Kabupaten Kolaka Timur',
                'Kabupaten Kolaka Utara',
                'Kabupaten Konawe',
                'Kabupaten Konawe Selatan',
                'Kabupaten Konawe Utara',
                'Kabupaten Konawe Kepulauan',
                'Kabupaten Muna',
                'Kabupaten Wakatobi',
                'Kota Bau-Bau',
                'Kota Kendari',
            ],
            'Sulawesi Utara' => [
                'Kabupaten Bolaang Mongondow',
                'Kabupaten Bolaang Mongondow Selatan',
                'Kabupaten Bolaang Mongondow Timur',
                'Kabupaten Bolaang Mongondow Utara',
                'Kabupaten Kepulauan Sangihe',
                'Kabupaten Kepulauan Siau Tagulandang Biaro',
                'Kabupaten Kepulauan Talaud',
                'Kabupaten Minahasa',
                'Kabupaten Minahasa Selatan',
                'Kabupaten Minahasa Tenggara',
                'Kabupaten Minahasa Utara',
                'Kota Bitung',
                'Kota Kotamobagu',
                'Kota Manado',
                'Kota Tomohon',
            ],
            'Sumatera Barat' => [
                'Kabupaten Agam',
                'Kabupaten Dharmasraya',
                'Kabupaten Kepulauan Mentawai',
                'Kabupaten Lima Puluh Kota',
                'Kabupaten Padang Pariaman',
                'Kabupaten Pasaman',
                'Kabupaten Pasaman Barat',
                'Kabupaten Pesisir Selatan',
                'Kabupaten Sijunjung',
                'Kabupaten Solok',
                'Kabupaten Solok Selatan',
                'Kabupaten Tanah Datar',
                'Kota Bukittinggi',
                'Kota Padang',
                'Kota Padangpanjang',
                'Kota Pariaman',
                'Kota Payakumbuh',
                'Kota Sawahlunto',
                'Kota Solok',
            ],
            'Sumatera Selatan' => [
                'Kabupaten Banyuasin',
                'Kabupaten Empat Lawang',
                'Kabupaten Lahat',
                'Kabupaten Muara Enim',
                'Kabupaten Musi Banyuasin',
                'Kabupaten Musi Rawas',
                'Kabupaten Ogan Ilir',
                'Kabupaten Ogan Komering Ilir',
                'Kabupaten Ogan Komering Ulu',
                'Kabupaten Ogan Komering Ulu Selatan',
                'Kabupaten Penukal Abab Lematang Ilir',
                'Kabupaten Ogan Komering Ulu Timur',
                'Kota Lubuklinggau',
                'Kota Pagar Alam',
                'Kota Palembang',
                'Kota Prabumulih',
            ],
            'Sumatera Utara' => [
                'Kabupaten Asahan' => [
                    'Bandar Pasir Mandoge',
                    '	Bandar Pulau',
                    '	Aek Songsongan',
                    'Rahuning',
                    '	Pulau Rakyat',
                    'Aek Kuasan',
                    '	Aek Ledong',
                    '	Sei Kepayang',
                    '	Sei Kepayang Barat',
                    '	Sei Kepayang Timur',
                    '	Tanjung Balai',
                    'Simpang Empat',
                    'Teluk Dalam',
                    'Air Batu',
                    '	Sei Dadap',
                    '	Buntu Pane',
                    'Tinggi Raja',
                    'Setia Janji',
                    'Meranti',
                    'Pulo Bandring',
                    'Rawang Panca Arga',
                    '	Air Joman',
                    'Silau Laut',
                    'Kota Kisaran Barat',
                    '	Kota Kisaran Timur',
                ],
                'Kabupaten Batubara' => [
                    '	Air Putih',
                    '	Datuk Lima Puluh',
                    '	Datuk Tanah Datar',
                    '	Laut Tador',
                    'Limapuluh',
                    '	Lima Puluh Pesisir',
                    '	Medang Deras',
                    'Nibung Hangus',
                    '	Sei Balai',
                    'Sei Suka',
                    'Talawi',
                    '	Tanjung Tiram',
                ],
                'Kabupaten Dairi' => [
                    '	Berampu',
                    'Gunung Sitember',
                    '	Lae Parira',
                    'Parbuluan',
                    'Pegagan Hilir',
                    '	Sidikalang',
                    '	Siempat Nempu',
                    'Siempat Nempu Hilir',
                    'Siempat Nempu Hulu',
                    'Silahisabungan',
                    '	Silima Pungga-Pungga',
                    '	Sitinjo',
                    'Sumbul',
                    'Tanah Pinem',
                    '	Tigalingga',
                ],
                'Kabupaten Deli Serdang' => [
                    '	Gunung Meriah',
                    'Tanjung Morawa',
                    '	Sibolangit',
                    '	Kutalimbaru',
                    '	Pancur Batu',
                    '	Namo Rambe',
                    '	Sibiru-biru',
                    'Sinembah Tanjung Muda Hilir',
                    '	Bangun Purba',
                    '	Galang',
                    'Sinembah Tanjung Muda Hulu',
                    '	Patumbak',
                    '	Deli Tua',
                    '	Sunggal',
                    'Hamparan Perak',
                    'Labuhan Deli',
                    '	Percut Sei Tuan',
                    '	Batang Kuis',
                    'Lubuk Pakam',
                    'Pagar Merbau',
                    '	Pantai Labu',
                    'Beringin',
                ],
                'Kabupaten Humbang Hasundutan' => [
                    'Bakti Raja',
                    'Dolok Sanggul',
                    'Lintong Nihuta',
                    'Onan Ganjang',
                    'Pakkat	',
                    'Paranginan',
                    'Parlilitan',
                    '	Pollung',
                    'Sijama Polang',
                    '	Tara Bintang',
                ],
                'Kabupaten Karo' => [
                    '	Barusjahe',
                    'Berastagi',
                    '	Dolat Rayat',
                    '	Juhar',
                    'Kabanjahe',
                    'Kuta Buluh',
                    '	Laubaleng',
                    '	Mardingding',
                    'Merdeka',
                    'Merek',
                    '	Munte',
                    'Naman Teran',
                    '	Payung',
                    'Simpang Empat',
                    '	Tiga Binanga',
                    'Tiganderket',
                    '	Tigapanah',
                ],
                'Kabupaten Labuhanbatu' => [
                    'Bilah Barat, Labuhanbatu',
                    'Bilah Hilir, Labuhanbatu',
                    'Bilah Hulu, Labuhanbatu',
                    'Pangkatan, Labuhanbatu',
                    'Panai Hilir, Labuhanbatu',
                    'Panai Hulu, Labuhanbatu',
                    'Panai Tengah, Labuhanbatu',
                    'Rantau Utara, Labuhanbatu',
                    'Rantau Selatan, Labuhanbatu',
                ],
                'Kabupaten Labuhanbatu Selatan' => [
                    'Kampung Rakyat, Labuhanbatu Selatan',
                    'Kotapinang, Labuhanbatu Selatan',
                    'Sungai Kanan, Labuhanbatu Selatan',
                    'Silangkitang, Labuhanbatu Selatan',
                    'Torgamba, Labuhanbatu Selatan',
                ],
                'Kabupaten Labuhanbatu Utara' => [
                    'Aek Kuo, Labuhanbatu Utara',
                    'Aek Natas, Labuhanbatu Utara',
                    'Kualuh Hilir, Labuhanbatu Utar',
                    'Kualuh Hulu, Labuhanbatu Uta',
                    'Kualuh Leidong, Labuhanbatu',
                    'Kualuh Selatan, Labuhanbatu',
                    'Marbau, Labuhanbatu Utara',
                    'Na IX-X, Labuhanbatu Utara',
                ],
                'Kabupaten Langkat' => [
                    'Babalan, Langkat',
                    'Bahorok, Langkat',
                    'Batang Serangan. Langkat',
                    'Brandan Barat, Langkat',
                    'Besitang, Langkat',
                    'Binjai, Langkat',
                    'Gebang, Langkat',
                    'Hinai, Langkat',
                    'Kuala, Langkat',
                    'Kutambaru. Langkat',
                    'Padang Tualang, Langkat',
                    'Pangkalan Susu, Langkat',
                    'Pematang Jaya, Langkat',
                    'Salapian, Langkat',
                    'Sawit Seberang, Langkat',
                    'Secanggang, Langkat',
                    'Sei Bingei, Langkat',
                    'Sei Lepan, Langkat',
                    'Selesai, Langkat',
                    'Sirapit, Langkat',
                    'Stabat, Langkat',
                    'Tanjung Pura, Langkat',
                    'Wampu, Langkat',
                ],
                'Kabupaten Mandailing Natal' => [
                    'Batahan, Mandailing Natal',
                    'Batang Natal, Mandaling Natal',
                    'Bukit Malintang, Mandailing Natal',
                    'Huta Bargot, Mandailing Natal',
                    'Kotanopan, Mandailing Natal',
                    'Lembah Sonik Marapi, Mandailing Natal',
                    'Lingga Bayu, Mandaling Natal',
                    'Muara Batang Gadis, Mandailing Natal',
                    'Muara Sipongi, Mandailing Natal',
                    'Naga Juang, Mandailing Natal',
                    'Natal, Mandailing Natal',
                    'Pakantan, Mandailing Natal',
                    'Panyabungan Barat, Mandailing Natal',
                    'Panyabungan Kota, Mandailing Natal',
                    'Panyabungan Selatan, Mandailing Natal',
                    'Panyabungan Timur, Mandailing Natal',
                    'Panyabungan Utara, Mandailing Natal',
                    'Puncak Sorik Marapi, Mandailing Natal',
                    'Ranto Baek, Mandailing Natal',
                    'Siabu, Mandailing Natal',
                    'Sinunukan. Mandailing Natal',
                    'Tambangan, Mandailing Natal',
                    'Ulu Pungkut, Mandailing Natal',
                ],
                'Kabupaten Nias' => [
        'Bawolato, Nias',
        'Botomuzoi, Nias',
        'Gido, Nias',
        'Hliduho, Nias',
        'Hili Serangkai, Nias',
        'Idanogawo, Nias',
        'Ma u, Nias',
        'Sogae adu, Nias',
        'Somolo-molo, Nias',
        'Ulugawo, Nias',
    ],
                'Kabupaten Nias Barat' => [
        'Lahomi, Nias Barat',
        'Lolofitu Moi, Nias Barat',
        'Mandrehe, Nias Barat',
        'Mandrehe Barat, Nias Barat',
        'Mandrehe Utara, Nias Barat',
        'Moro o, Nias Barat',
        'Sirombu, Nias Barat',
        'Ulu Moro o, Nias Barat',
    ],
                'Kabupaten Nias Selatan' => [
        'Amandraya, Nias Selatan',
        'Aramo, Nias Selatan',
        'Boronadu, Nias Selatan',
        'Fanayama, Nias Selatan',
        'Gomo, Nias Selatan',
        'Hibala, Nias Selatan',
        'Hilimegai, Nias Selatan',
        'Hlisalawa ahe, Nias Selatan',
        'Huruna, Nias Selatan',
        'Idanotae, Nias Selatan',
        'Lahusa, Nias Selatan',
        'Lolomatua, Nias Selatan',
        'Lolowau, Nias Selatan',
        'Luahagundre Maniamolo, Nias Selatan',
        'Manian amolo, Nias Selatan',
        'Mazino, Nias Selatan',
        'Mazo, Nias Selatan',
        'O o u, Nias Selatan',
        'Onohazumba. Nias Selatan',
        'Onolalu, Nias Selatan',
        'Pulau-Pulau Batu, Nias Selatan',
        'Pulau-Pulau Batu Barat, Nias Selatan',
        'Pulau-Pulau Batu Timur, Nias Selatan',
        'Pulau-Pulau Batu Utara, Nias Selatan',
        'Sidua ori, Nias Selatan',
        'Simuk, Nias Selatan',
        'Somambawa, Nias Selatan',
        'Susua, Nias Selatan',
        'Tanah Masa, Nias Selatan',
        'Teluk Dalam, Nias Selatan',
        'Toma, Nias Selatan',
        'Ulunoyo, Nias Selatan',
        'Ulu Idanotae, Nias Selatan',
        'Umbunasi, Nias Selatan',
        'Ulususua, Nias Selatan',
    ],
                'Kabupaten Nias Utara' => [
        'Afulu, Nias Utara',
        'Alasa, Nias Utara',
        'Alasa Talumuzoi,
        Nias Utara',
                   'Lahewa, Nias Utara',
                   'Lahewa Timur, Nias Utara',
                   'Lotu, Nias Utara',
                   'Namohalu Esiwa, Nias Utara',
                   'Sawo, Nias Utara',
                   'Sitolu Ori, Nias Utara',
                   'Tugala Oyo, Nias Utara',
                   'Tuhemberua, Nias Utara',
                ],
                'Kabupaten Padang Lawas' => [
        'Aek Nabara Barumun',
        'Barumun',
        'Barumun Barat',
        'Barumun Baru',
        'Barumun in Selatan',
        'Barumun Tengah',
        'Batang Lubu Sutam',
        'Huristak',
        'Huta Raja Tinggi',
        'Lubuk Barumun',
        'Sihapas Barumun',
        'Sosa',
        'Sosa Julu',
        'Sosa Timur',
        'Sosopan',
        'Ulu Barumun',
        'Ulu Sosa',
    ],
                'Kabupaten Padang Lawas Utara' => [
        'Batang Onang, Padang Lawas Utara',
        'Dolok, Padang Lawas Utara',
        'Dolok Sigompulon, Padang Lawas Utara',
        'Halongonan, Padang Lawas Utara',
        'Halongonan Timur, Padang Lawas Utara',
        'Hulu Sihapas, Padang Lawas Utara',
        'Padang Bolak, Padang Lawas Utara',
        'Padang Bolak Julu, Padang Lawas Utara',
        'Padang Bolak Tenggara, Padang Lawas Utara',
        'Portibi, Padang Lawas Utara',
        'Simangambat, Padang Lawas Utara',
        'Ujung Batu, Padang Lawas Utara',
    ],
                'Kabupaten Pakpak Bharat' => [
        'Kerajaan',
        'Pagindar',
        'Pergetteng Getteng Sengkut',
        'Salak',
        'Siem pat Rube',
        'Sitelu Tali Urang Jehe',
        'Sitelu Tali Urang Julu',
        'Tinada',
    ],
                'Kabupaten Samosir' => [
        'Harian, Samosir',
        'Nainggolan, Samosir',
        'Onan Runggu, Samosir',
        'Palipi, Samosir',
        'Pangururan, Samosir',
        'Ronggur Nihuta, Samosir',
        'Sianjar Mula Mula, Samosir',
        'Simanindo, Samosir',
        'Sitio-tio, Samosir',
    ],
                'Kabupaten Serdang Bedagai' => [
        'Bandar Khalipah, Serdang Bedagai',
        'Bintang Bayu, Serdang Bedagai',
        'Dolok Masihul, Serdang Bedagai',
        'Dolok Merawan. n. Serdang Bedagai',
        'Kotarih, Serdang Bedagai',
        'Pantai Cermin, Serdang Bedagai',
        'Pegaiahan. Serdang Bedagai',
        'Perbaungan, Serdang Bedagai',
        'Sei Bamban. Serdang Bedagai',
        'Sei Rampah, Serdang Bedagai',
        'Serba Jadi, Serdang Bedagai',
        'Silinda, Serdang Bedagai',
        'Sipispis, Serdang Bedagai',
        'Tanjung Beringin, Serdang Bedagai',
        'Tebing Syahbandar, Serdang Bedagai',
        'Tebing Tinggi, Serdang Bedagai',
        'Teluk Mengkudu, Serdang Bedagai',
    ],
                'Kabupaten Simalungun' => [
        'Bandar, Simalungun',
        'Bandar Huluan, Simalungun',
        'Bandar Masilam, Simalungun',
        'Bosar Maligas, Simalungun',
        'Dolog Masagal, Simalungun',
        'Dolok Batu Nanggar, Simalungun',
        'Dolok Panribuan, Simalungun',
        'Dolok Pardamean, Simalungun',
        'Dolok Silau, Simalungun',
        'Girsang Sipangan Bolon, Simalungun',
        'Gunung Malela, Simalungun',
        'Gunung Maligas, Simalungun',
        'Haranggaol Horison, Simalungun',
        'Hatonduhan, Simalungun',
        'Huta Bayu Raja, Simalungun',
        'Jawa Maraja Bah Jambi, Simalungun',
        'Jorlang Hataran, Simalungun',
        'Panei, Simalungun',
        'Pamatang Silima Huta, Simalungun',
        'Panombeian Panei, Simalungun',
        'Pematang Bandar, Simalungun',
        'Pematang Sidamanik, Simalungun',
        'Purba, Simalungun',
        'Raya, Simalungun',
        'Raya Kahean, Simalungun',
        'Siantar, Simalungun',
        'Sidamanik, Simalungun',
        'Silimakuta, Simalungun',
        'Silau Kahean, Simalungun',
        'Tanah Jawa, Simalungun',
        'Tapian Dolok, Simalungun',
        'Ujung Padang, Simalungun',
    ],
                'Kabupaten Tapanuli Selatan' => [
        'Aek Bilah, Tapanuli Selatan',
        'Angkola Barat, Tapanuli Selatan',
        'Angkola Sangkunur, Tapanuli Selata',
        'Angkola Selatan, Tapanuli Selatan',
        'Angkola Timur, Tapanuli Selatan',
        'Arse, Tapanuli Selatan',
        'Batang Angkola, Tapanuli Selatan',
        'Batang Toru, Tapanuli Selatan',
        'Marancar, Tapanuli Selatan',
        'Muara Batang Toru, Tapanuli Selatan',
        'Saipar Dolok Hole, Tapanuli Selatan',
        'Sayur Matinggi, Tapanuli Selatan',
        'Sipirok, Tapanuli Selatan',
        'Tano Tombangan Angkola, Tapanuli Selatan',
    ],
                'Kabupaten Tapanuli Tengah' => [
        'Andam Dewi',
        'Badiri',
        'Barus',
        'Barus Utara',
        'Kolang',
        'Lumut',
        'Manduamas',
        'Pandan',
        'Pasaribu Tobing',
        'Pinangsori',
        'Sarudik',
        'Sibabangun',
        'Sirandorung',
        'Sitahuis',
        'Sosor Gadong',
        'Sorkam',
        'Sorkam Barat',
        'Sukabangun',
        'Tapian Nauli',
        'Tukka',
    ],
                'Kabupaten Tapanuli Utara' => [
        'Adian Koting',
        'Garoga',
        'Muara',
        'Pagaran',
        'Pahae Jae',
        'Pahae Julu',
        'Pangaribuan',
        'Parmonangan',
        'Purba Tua',
        'Siatas Barita',
        'Siborong-Borong',
        'Simangumba',
        'Sipahutar',
        'Sipoholon',
        'Tarutung',
    ],
                'Kabupaten Toba Samosir' => [
        'Ajibata',
        'Balige',
        'Bonatua Lunasi',
        'Borbor',
        'Habinsaran',
        'Laguboti',
        'Lumban Julu',
        'Nassau',
        'Parmaksian',
        'Pintu Pohan Meranti',
        'Porsea',
        'Siantar Narumonda',
        'Sigumpar',
        'Silaen',
        'Tampahan',
        'Uluan',
    ],
                'Kota Binjai' => [
        'Binjai Barat',
        'Binjai Kota',
        'Binjai Selatan',
        'Binjai Timur',
        'Binjai Utara',
    ],
                'Kota Gunungsitoli' => [
        'Gunungsitoli',
        'Gunungsitoli Alo oa',
        'Gunungsitoli Barat',
        'Gunungsitoli Idanoi',
        'Gunungsitoli Selatan',
        'Gunungsitoli Utara',
    ],
                'Kota Medan' => [
        'Medan Amplas',
        'Medan Area',
        'Medan Barat',
        'Medan Baru',
        'Medan Belawan',
        'Medan Deli',
        'Medan Denai',
        'Medan Helvetia',
        'Medan Johor',
        'Medan Kota',
        'Medan Labuhan',
        'Medan Maimun',
        'Medan Marelan',
        'Medan Perjuangan',
        'Medan Petisah',
        'Medan Polonia',
        'Medan Sunggal',
        'Medan Selayang',
        'Medan Tembung',
        'Medan Tuntungan',
        'Medan Timur',
    ],
                'Kota Padangsidempuan' => [
        'Padangsidimpuan Angkola Julu',
        'Padangsidimpuan Batunadua',
        'Padangsidimpuan Hutaimbaru',
        'Padangsidimpuan Selatan',
        'Padangsidimpuan Tenggara',
        'Padangsidimouan Utara',
    ],
                'Kota Pematangsiantar' => [
        'Siantar Barat',
        'Siantar Marihat',
        'Siantar Marimbun',
        'Siantar Martoba',
        'Siantar Selatan',
        'Siantar Sitalasari',
        'Siantar Timur',
        'Siantar Utara',
    ],
                'Kota Sibolga' => [
        'Sibolga Kota',
        'Sibolga Sambas',
        'Sibolga Selatan',
        'Sibolga Utara',
    ],
                'Kota Tanjungbalai' => [
        'Datuk Bandar',
        'Datuk Bandar Timur',
        'Sei Tualang Raso',
        'Tanjungbalai Selatan',
        'Tanjungbalai Utara',
        'Teluk Nibung',
    ],
                'Kota Tebing Tinggi' => [
        'Bajenis',
        'Padang Hilir',
        'Padang Hulu',
        'Rambutan',
        'Tebing Tinggi Kota',
    ],
            ]
        ];
    }
}

if ( ! function_exists('get_list_option_city')) {
    function get_list_option_city($value = null)
    {
        $result = '';
        $list_city = get_list_city();
        foreach ($list_city as $province => $list_city) {
            $result .= '<optgroup label="' . $province . '">';
            foreach ($list_city as $city) {
                $selected = '';
                if ($value == $city) {
                    $selected = ' selected ';
                }
                $result .= '<option '.$selected.' value="'.$city.'">' . $city . '</option>';
            }
            $result .= '</optgroup>';
        }
        return $result;
    }
}

if ( ! function_exists('get_list_city2')) {
    function get_list_city2()
    {
        $result = [];
        $list_city = get_list_city();
        foreach ($list_city as $province => $list_city) {
            foreach ($list_city as $city) {
                $result[$province][$city] = $city;
            }
        }
        return $result;
    }
}

if ( ! function_exists('get_list_gender')) {
    function get_list_gender()
    {
        return [
            'male' => __('male'),
            'female' => __('female')
        ];
    }
}

if ( ! function_exists('get_list_status_project')) {
    function get_list_status_project()
    {
        return [
            1 => __('general.active'),
            2 => __('general.inactive'),
        ];
    }
}

if ( ! function_exists('get_list_status_feedback')) {
    function get_list_status_feedback()
    {
        return [
            1 => __('general.pending'),
            2 => __('general.on_progress'),
            5 => __('general.complete'),
            8 => __('general.rejected').'('.__('general.review').')',
            9 => __('general.rejected'),
        ];
    }
}

if ( ! function_exists('get_list_status_feedback2')) {
    function get_list_status_feedback2()
    {
        return [
            1 => __('general.pending'),
            2 => __('general.on_progress'),
            5 => __('general.complete'),
        ];
    }
}

if ( ! function_exists('get_list_status_feedback3')) {
    function get_list_status_feedback3()
    {
        return [
            8 => __('general.rejected').'('.__('general.review').')',
            9 => __('general.rejected'),
        ];
    }
}

if ( ! function_exists('get_list_status_feedback_one_one')) {
    function get_list_status_feedback_one_one()
    {
        return [
            1 => __('general.pending'),
            2 => __('general.on_progress'),
            4 => __('general.waiting_calibration'),
            5 => __('general.complete').' C Level',
            6 => __('general.need_recalibrate'),
            7 => __('general.recalibrate'),
            8 => __('general.complete').' N-1',
            9 => __('general.rejected'),
        ];
    }
}

if ( ! function_exists('get_list_month_id')) {
    function get_list_month_id($month)
    {
        $list_month = [
            1 => 'Januari',
            2 => 'Febuari',
            4 => 'Maret',
            5 => 'April',
            6 => 'Mei',
            7 => 'Juni',
            8 => 'Juli',
            9 => 'Augustus',
            10 => 'Oktober',
            11 => 'November',
            12 => 'Desember',
        ];
        $month = intval($month);
        return isset($list_month[$month]) ? $list_month[$month] : '';
    }
}
